### ISSUE TITLE
Decentralized LoRa gateway

### ISSUE THREAD

**Issue by heezes** [ONEARMY/project-kamp-weather-station#9]
What is the current project status?
I think I  can help with the central gateway which would transport our data from the child node to remote server.

I have some questions though:

- What is current backend system design? (Is is firebase firestore or are you open to changes)
- What are the connectivity options available at gateway end (Wi-Fi, Gprs, Ethernet)?
- Are there any plans available for data protocol over LoRa

Thanks

**Comment by Anze-** [comment]
Hi @heezes ! Did you know about the Discord channel? https://discord.com/channels/586676777334865928/827224018322194529/827250652182216724

At the moment we are developing the LoRa and testing sensors.. we need more help with the wind sensor and the LoRa protocol!

At the moment there's no stable internet connection at the camp. So no remote server at the moment.. all local. So it's wifi for the end users and LoRa to connect between sensor nodes!

We'll wait for you on Discord! :) Thanks for reaching out!!

**Comment by heezes** [comment]
@Anze-  Cool! Will join the server.
Thanks
